import java.util.ArrayList;

public class GUI extends javax.swing.JFrame
{   
    private int rounds;
    private DecisionEngine engine;
    private static ResultDatabase history;
    
    public GUI() 
    {
        history = new ResultDatabase();
        initComponents();
        layerPane.getComponentsInLayer(1)[0].setVisible(false); // hide main menu for now
    }
    
    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerPane = new javax.swing.JLayeredPane();
        gamePanel = new javax.swing.JPanel();
        roundHistoryPanel = new javax.swing.JPanel();
        roundHistoryLabel = new javax.swing.JLabel();
        aboveHistoryListLabel = new javax.swing.JLabel();
        predictionLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        roundHistoryScrollPane = new javax.swing.JScrollPane();
        roundHistoryList = new javax.swing.JList();
        menuPanel = new javax.swing.JPanel();
        rockButton = new javax.swing.JButton();
        paperButton = new javax.swing.JButton();
        scissorsButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(15, 15), new java.awt.Dimension(10, 32767));
        helpButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        initialPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        aiChoiceList = new javax.swing.JScrollPane();
        aiField = new javax.swing.JList();
        roundsLabel = new javax.swing.JLabel();
        aiLabel = new javax.swing.JLabel();
        roundsField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock Paper Scissors");

        gamePanel.setLayout(new java.awt.BorderLayout());

        roundHistoryPanel.setMaximumSize(new java.awt.Dimension(32765, 32765));

        roundHistoryLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        roundHistoryLabel.setText("Round History");

        aboveHistoryListLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aboveHistoryListLabel.setText("Round | Your Choice | Computer's Choice | Result");

        predictionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        predictionLabel.setText("The computer predicted you would choose scissors.");

        scoreLabel.setBackground(new java.awt.Color(250, 250, 250));
        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scoreLabel.setText("Wins:          Losses:          Draws:    ");

        roundHistoryList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roundHistoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        roundHistoryList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roundHistoryScrollPane.setViewportView(roundHistoryList);

        javax.swing.GroupLayout roundHistoryPanelLayout = new javax.swing.GroupLayout(roundHistoryPanel);
        roundHistoryPanel.setLayout(roundHistoryPanelLayout);
        roundHistoryPanelLayout.setHorizontalGroup(
            roundHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(predictionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(roundHistoryPanelLayout.createSequentialGroup()
                        .addGroup(roundHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roundHistoryScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundHistoryLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboveHistoryListLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundHistoryPanelLayout.setVerticalGroup(
            roundHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundHistoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboveHistoryListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundHistoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(predictionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scoreLabel))
        );

        gamePanel.add(roundHistoryPanel, java.awt.BorderLayout.PAGE_START);

        menuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rockButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rockButton.setText("Rock");
        rockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockButtonActionPerformed(evt);
            }
        });
        menuPanel.add(rockButton);

        paperButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paperButton.setText("Paper");
        paperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperButtonActionPerformed(evt);
            }
        });
        menuPanel.add(paperButton);

        scissorsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scissorsButton.setText("Scissors");
        scissorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsButtonActionPerformed(evt);
            }
        });
        menuPanel.add(scissorsButton);
        menuPanel.add(filler1);

        helpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        menuPanel.add(helpButton);

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        menuPanel.add(exitButton);

        gamePanel.add(menuPanel, java.awt.BorderLayout.PAGE_END);

        gamePanel.setBounds(0, 0, 450, 600);
        layerPane.add(gamePanel, new Integer(1));

        aiField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        aiField.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Smart", "Random" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        aiField.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        aiChoiceList.setViewportView(aiField);

        roundsLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        roundsLabel.setText("Enter the number of rounds:");

        aiLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        aiLabel.setText("Select the AI Engine to use:");

        roundsField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setActionCommand("cancelButton");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        okButton.setText("OK");
        okButton.setActionCommand("okButton");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundsLabel)
                            .addComponent(aiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aiChoiceList, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(roundsField)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addGap(77, 77, 77)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aiLabel)
                    .addComponent(aiChoiceList, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundsLabel)
                    .addComponent(roundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelButton)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout initialPanelLayout = new javax.swing.GroupLayout(initialPanel);
        initialPanel.setLayout(initialPanelLayout);
        initialPanelLayout.setHorizontalGroup(
            initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initialPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        initialPanelLayout.setVerticalGroup(
            initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialPanelLayout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        initialPanel.setBounds(0, 160, 430, 460);
        layerPane.add(initialPanel, new Integer(2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Integer rounds = null;
        String engType = (String) aiField.getSelectedValue();
        try { rounds = Integer.valueOf(roundsField.getText()); }
        catch (NumberFormatException e) {}
        
        if (engType != null && rounds != null) 
        {
            layerPane.getComponentsInLayer(2)[0].setVisible(false); // hide initial prompt
            this.rounds = rounds;
            this.engine = DecisionEngine.make(engType);
            layerPane.getComponentsInLayer(1)[0].setVisible(true); // show main menu
        }
    }//GEN-LAST:event_okButtonActionPerformed
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

private void paperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperButtonActionPerformed
    processChoice(Choice.PAPER);
}//GEN-LAST:event_paperButtonActionPerformed

private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // Replace the list object with help instructions or open dialog box
}//GEN-LAST:event_helpButtonActionPerformed

private void rockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockButtonActionPerformed
    processChoice(Choice.ROCK);
}//GEN-LAST:event_rockButtonActionPerformed

private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
    setVisible(false);
    dispose();
    System.exit(0);
}//GEN-LAST:event_exitButtonActionPerformed

private void scissorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsButtonActionPerformed
    processChoice(Choice.SCISSORS);
}//GEN-LAST:event_scissorsButtonActionPerformed

    private void processChoice(Choice choice)
    {
        switch (choice.getValue()) 
        {
            case 1:
            case 2:
            case 3:
                --this.rounds;
                Result result = new Result(choice, engine.getComputerChoice(history));
                history.add(result);
                roundHistoryList.set
                // TODO update the display
                if (this.rounds == 0) 
                {
                    // works | layerPane.getComponentsInLayer(1)[0].setVisible(false);
                    // alter the display to indicate the match is over
                }
                break;
            case 4:
                // TODO show help menu
                break;
            case 6:
                System.exit(0);                 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboveHistoryListLabel;
    private javax.swing.JScrollPane aiChoiceList;
    private javax.swing.JList aiField;
    private javax.swing.JLabel aiLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel initialPanel;
    private javax.swing.JLayeredPane layerPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton paperButton;
    private javax.swing.JLabel predictionLabel;
    private javax.swing.JButton rockButton;
    private javax.swing.JLabel roundHistoryLabel;
    private javax.swing.JList roundHistoryList;
    private javax.swing.JPanel roundHistoryPanel;
    private javax.swing.JScrollPane roundHistoryScrollPane;
    private javax.swing.JTextField roundsField;
    private javax.swing.JLabel roundsLabel;
    private javax.swing.JButton scissorsButton;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
